"use client"
// This component was generated by @sitecore-search/cli on Tue Aug 27 2024 11:45:52 GMT+0200 (Central European Summer Time)
import { useRouter } from 'next/navigation'

import type { ActionProp, ItemClickedAction } from '@sitecore-search/react';
import { ArticleCard } from '@sitecore-search/ui';
import Image from 'next/image'
import { DEFAULT_IMG_URL } from '@/app/_data/customizations';

type ArticleCardItemCardProps = {
  className?: string;
  displayText?: boolean;
  article: any;
  onItemClick: ActionProp<ItemClickedAction>;
  index: number;
};

const ArticleHorizontalItemCard = ({ className = '', article, onItemClick, index }: ArticleCardItemCardProps) => {
  const router = useRouter();
  const validImageUrl = article.image_url?.trim() ? article.image_url : DEFAULT_IMG_URL;

  return (
    <ArticleCard.Root
      key={article.id}
      className={`group flex flex-row p-4 my-4 flex-nowrap max-h-52 w-full relative border border-card-edge rounded-md bg-white transition-shadow duration-200 ease-linear hover:shadow-[6px_6px_0_0_var(--color-card-accent)] focus-within:shadow-[6px_6px_0_0_var(--color-card-accent)] ${className}`}
    >
      <div className="w-[25%] flex-none overflow-hidden rounded-md bg-gray-200">
        <Image
          src={validImageUrl}
          className="h-full w-full object-cover object-center lg:h-full lg:w-full"
          alt='alt'
          width={500}
          height={115}
        />
      </div>
      {article.type && (
        <span className="absolute top-4 right-4 z-10 max-w-[40%] truncate text-xs uppercase tracking-wide text-card-body/70">
          {article.type}
        </span>
      )}
      <div className="pl-4 pr-24 grow flex-col">
        <a
          className="focus:outline-indigo-500"
          href={article.url}
          onClick={(event) => {
            event.preventDefault();
            onItemClick({
              id: article.id,
              index,
              sourceId: article.source_id,
            });
            router.push(`/detail/${article.id}`);
          }}
        >
          <span aria-hidden="true" className="absolute inset-0"></span>
          <ArticleCard.Title className="text-base font-bold text-card-title">
            {article.name || article.title}
          </ArticleCard.Title>
        </a>
        <ArticleCard.Subtitle className="mt-3 text-sm text-card-body line-clamp-3">
          {article.subtitle || article.description}
        </ArticleCard.Subtitle>
      </div>
    </ArticleCard.Root>
  );
};
export default ArticleHorizontalItemCard;
