"use client"
// This component was generated by @sitecore-search/cli on Mon Aug 26 2024 13:33:05 GMT+0200 (Central European Summer Time)
import { useRouter } from 'next/navigation'; 

import { usePreviewSearchActions } from '@sitecore-search/react';
import { PreviewSearch } from '@sitecore-search/ui';

type SuggestionBlockProps = {
  items: Array<{ text: string }>;
  title: string;
  blockId: string;
  filterAttribute?: string;
  disabled?: boolean;
};

const SuggestionBlock = ({ items, title, blockId, filterAttribute, disabled }: SuggestionBlockProps) => {
  const { onSuggestionClick } = usePreviewSearchActions();
  const router = useRouter();
  return (
    <>
      {items.length > 0 && (
        <PreviewSearch.SuggestionsGroup className="flex flex-1 flex-col p-2" id={blockId} filterAttribute={filterAttribute}>
          <h2 className="box-border pl-1 block text-lg font-bold m-2">{title}</h2>
          {items.map(({ text }) => (
            <PreviewSearch.SuggestionTrigger
              className="cursor-pointer mb-2 rounded-md border border-card-edge bg-white p-2 text-sm transition-shadow duration-200 ease-linear data-[state=active]:outline-none data-[state=active]:text-card-title data-[state=active]:shadow-[6px_6px_0_0_var(--color-card-accent)] focus:outline-none focus:text-card-title focus:shadow-[6px_6px_0_0_var(--color-card-accent)] hover:outline-none hover:text-card-title hover:shadow-[6px_6px_0_0_var(--color-card-accent)]"
              id={text}
              key={text}
              asChild
              disabled={disabled}
            >
              <a
                onClick={() => {
                  onSuggestionClick({
                    name: blockId,
                    title,
                    value: text,
                    displayName: text,
                  });
                  router.push('/search?q=' + text);
                }}
              >
                {text}
              </a>
            </PreviewSearch.SuggestionTrigger>
          ))}
        </PreviewSearch.SuggestionsGroup>
      )}
    </>
  );
};

export default SuggestionBlock;
